./client $1 Онцгой
./client $1 комисс
./client $1 өнөөдөр
./client $1 11:00
./client $1 цагаас
./client $1 коронавирусийн
./client $1 шинэ
./client $1 хувилбар
./client $1 болох
./client $1 "Омикрон"
./client $1 мутац
./client $1 олон
./client $1 улсад
./client $1 бүртгэгдсэнтэй
./client $1 холбогдуулан
./client $1 хуралдлаа.
./client $1 Хурлаас
./client $1 гарсан
./client $1 шийдвэрийг
./client $1 танилцуулж
./client $1 байна.
./client $1 hello
